import { defaultLeagueSettings } from "./defaults";
import type { LineupPlayer, Player, TeamSummary } from "./types";

export const teams: TeamSummary[] = [
  {
    id: "team-1",
    leagueId: "league-1",
    leagueName: "Sunday Night Rotisserie",
    teamName: "Golden Sombreros",
    managerName: "Alex",
    scoringType: "h2h-categories",
    record: "7-4-1",
    rank: 3,
    matchup: {
      opponentName: "Warning Track Power",
      userScore: 6,
      opponentScore: 4,
      periodLabel: "Week 13",
      progressPercent: 62,
    },
  },
  {
    id: "team-2",
    leagueId: "league-2",
    leagueName: "Warehouse Points League",
    teamName: "Launch Angle Lab",
    managerName: "Alex",
    scoringType: "h2h-points",
    record: "8-3",
    rank: 1,
    matchup: {
      opponentName: "Bullpen Cartel",
      userScore: 188.5,
      opponentScore: 171.2,
      periodLabel: "Week 13",
      progressPercent: 58,
    },
  },
  {
    id: "team-3",
    leagueId: "league-3",
    leagueName: "Old School 5x5",
    teamName: "Box Score Poets",
    managerName: "Alex",
    scoringType: "roto",
    record: "86 pts",
    rank: 5,
    matchup: {
      opponentName: "Season Standings",
      userScore: 86,
      opponentScore: 112,
      periodLabel: "Season",
      progressPercent: 48,
    },
  },
];

export const players: Player[] = [
  {
    id: "player-1",
    name: "Julio Rodriguez",
    mlbTeam: "SEA",
    positions: ["OF"],
    status: "active",
    availability: "rostered",
    newsHeadline: "Homered and stole a base in Monday's win.",
    seasonStats: { R: 54, HR: 18, RBI: 52, SB: 17, AVG: ".276" },
    projectedStats: { R: 42, HR: 15, RBI: 44, SB: 12, AVG: ".270" },
  },
  {
    id: "player-2",
    name: "Corbin Carroll",
    mlbTeam: "ARI",
    positions: ["OF"],
    status: "day-to-day",
    availability: "free-agent",
    newsHeadline: "Held out after fouling a ball off his foot.",
    seasonStats: { R: 49, HR: 13, RBI: 41, SB: 21, AVG: ".263" },
    projectedStats: { R: 39, HR: 10, RBI: 34, SB: 18, AVG: ".258" },
  },
  {
    id: "player-3",
    name: "Spencer Strider",
    mlbTeam: "ATL",
    positions: ["SP", "P"],
    status: "injured",
    availability: "rostered",
    newsHeadline: "Throwing progression continues without setback.",
    seasonStats: { W: 8, SV: 0, K: 132, ERA: "3.31", WHIP: "1.08" },
    projectedStats: { W: 5, SV: 0, K: 83, ERA: "3.42", WHIP: "1.11" },
  },
  {
    id: "player-4",
    name: "Andres Munoz",
    mlbTeam: "SEA",
    positions: ["RP", "P"],
    status: "active",
    availability: "waivers",
    newsHeadline: "Picked up another ninth-inning save chance.",
    seasonStats: { W: 2, SV: 18, K: 46, ERA: "2.14", WHIP: "0.93" },
    projectedStats: { W: 1, SV: 12, K: 32, ERA: "2.60", WHIP: "1.01" },
  },
  {
    id: "player-5",
    name: "Elly De La Cruz",
    mlbTeam: "CIN",
    positions: ["SS", "3B"],
    status: "active",
    availability: "rostered",
    newsHeadline: "Continues to lead off against right-handed pitching.",
    seasonStats: { R: 58, HR: 15, RBI: 45, SB: 34, AVG: ".251" },
    projectedStats: { R: 43, HR: 12, RBI: 38, SB: 25, AVG: ".247" },
  },
  {
    id: "player-6",
    name: "Adley Rutschman",
    mlbTeam: "BAL",
    positions: ["C"],
    status: "active",
    availability: "rostered",
    newsHeadline: "Reached base three times while batting second.",
    seasonStats: { R: 46, HR: 11, RBI: 48, SB: 1, AVG: ".281" },
    projectedStats: { R: 32, HR: 9, RBI: 35, SB: 1, AVG: ".275" },
  },
  {
    id: "player-7",
    name: "Freddie Freeman",
    mlbTeam: "LAD",
    positions: ["1B"],
    status: "active",
    availability: "rostered",
    newsHeadline: "Doubled twice in another multi-hit game.",
    seasonStats: { R: 55, HR: 13, RBI: 57, SB: 4, AVG: ".302" },
    projectedStats: { R: 42, HR: 11, RBI: 43, SB: 3, AVG: ".296" },
  },
  {
    id: "player-8",
    name: "Tarik Skubal",
    mlbTeam: "DET",
    positions: ["SP", "P"],
    status: "active",
    availability: "rostered",
    newsHeadline: "Scheduled for a two-start week.",
    seasonStats: { W: 9, SV: 0, K: 118, ERA: "2.74", WHIP: "0.96" },
    projectedStats: { W: 6, SV: 0, K: 89, ERA: "3.02", WHIP: "1.03" },
  },
];

export const lineup: LineupPlayer[] = [
  { slot: "C", player: players[5], matchupTotal: 7.5 },
  { slot: "1B", player: players[6], matchupTotal: 12.0 },
  { slot: "OF", player: players[0], matchupTotal: 18.4 },
  { slot: "SS", player: players[4], matchupTotal: 15.3 },
  { slot: "SP", player: players[7], matchupTotal: 22.6 },
  { slot: "RP", player: players[3], matchupTotal: 9.2 },
  { slot: "BN", player: players[1], matchupTotal: 4.1 },
  { slot: "IL", player: players[2], matchupTotal: 0 },
];

export const leagueStandings = [
  { team: "Launch Angle Lab", record: "8-3", points: 112 },
  { team: "Warning Track Power", record: "7-4", points: 103 },
  { team: "Golden Sombreros", record: "7-4-1", points: 97 },
  { team: "Bullpen Cartel", record: "6-5", points: 91 },
  { team: "Box Score Poets", record: "5-6", points: 86 },
];

export const mockLeagueSettings = {
  ...defaultLeagueSettings,
  id: "league-1",
  name: "Sunday Night Rotisserie",
};
